import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { TOOL_DEFINITIONS } from '../src/server.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

type AnyZod = z.ZodTypeAny;

function getTypeName(field: AnyZod): string {
  const type: string = (field._def as { type: string }).type;
  switch (type) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return 'array';
    case 'object': return 'object';
    case 'record': return 'record';
    case 'enum': return 'enum';
    case 'optional': return getTypeName((field as z.ZodOptional<AnyZod>).unwrap());
    case 'default': return getTypeName((field._def as { innerType: AnyZod }).innerType);
    default: return type ?? 'unknown';
  }
}

function unwrap(field: AnyZod): AnyZod {
  const type: string = (field._def as { type: string }).type;
  if (type === 'optional') return unwrap((field as z.ZodOptional<AnyZod>).unwrap());
  if (type === 'default') return unwrap((field._def as { innerType: AnyZod }).innerType);
  return field;
}

function formatParam(name: string, field: AnyZod, indent: string): string {
  const type = getTypeName(field);
  const required = field.isOptional() ? 'optional' : 'required';
  const desc = field.description ?? '';
  const line = `${indent}- \`${name}\` (${type}, ${required})${desc ? ` — ${desc}` : ''}`;

  const inner = unwrap(field);
  const innerType: string = (inner._def as { type: string }).type;

  if (innerType === 'array') {
    const element = (inner._def as { element: AnyZod }).element;
    const elementType: string = (element._def as { type: string }).type;
    if (elementType === 'object') {
      const shape = (element._def as { shape: Record<string, AnyZod> }).shape;
      const subLines = Object.entries(shape).map(([k, v]) =>
        formatParam(k, v, indent + '  ')
      );
      return [line, ...subLines].join('\n');
    }
  }

  if (innerType === 'object') {
    const shape = (inner._def as { shape: Record<string, AnyZod> }).shape;
    const subLines = Object.entries(shape).map(([k, v]) =>
      formatParam(k, v, indent + '  ')
    );
    return [line, ...subLines].join('\n');
  }

  return line;
}

function formatToolSection(name: string, def: { description: string; inputSchema: z.ZodObject<z.ZodRawShape> }): string {
  const lines: string[] = [`## ${name}`, def.description, ''];

  const shape = def.inputSchema.shape;
  const entries = Object.entries(shape);

  if (entries.length === 0) {
    lines.push('**Input:** *(none)*');
  } else {
    lines.push('**Input:**');
    for (const [fieldName, fieldSchema] of entries) {
      lines.push(formatParam(fieldName, fieldSchema as AnyZod, ''));
    }
  }

  lines.push('', '---', '');
  return lines.join('\n');
}

const header = `<!-- Generated by scripts/generate-tools-docs.ts — do not edit manually -->
# MCP Tools

`;

const sections = Object.entries(TOOL_DEFINITIONS)
  .map(([name, def]) => formatToolSection(name, def))
  .join('\n');

const output = header + sections;

const outPath = join(__dirname, '../docs/tools.md');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, output, 'utf-8');
console.log(`Written: ${outPath}`);
